import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('真实本地 API：MOCK 成功、重复点击、刷新、故障证据与报告导出', async ({ page }) => {
  const tokenFile = process.env.D1ENV_E2E_TOKEN_FILE;
  if (!tokenFile) throw new Error('缺少本地 E2E 引导文件；此测试未验证，不可计为通过');
  const token = (await readFile(tokenFile, 'utf8')).trim();
  let submissionCount = 0;
  const keys: string[] = [];
  const planIds: string[] = [];
  page.on('request', (request) => {
    if (new URL(request.url()).pathname === '/api/jobs' && request.method() === 'POST') {
      submissionCount += 1;
      keys.push((request.postDataJSON() as { idempotency_key: string }).idempotency_key);
      planIds.push((request.postDataJSON() as { plan_id: string }).plan_id);
    }
  });
  await page.goto(`/#bootstrap=${encodeURIComponent(token)}`);
  await expect(page.getByRole('button', { name: '下一步：机器人配置' })).toBeEnabled();
  expect(new URL(page.url()).hash).toBe('');
  await expect(page.getByTestId('mock-watermark')).toContainText('MOCK');
  await page.getByRole('button', { name: '下一步：机器人配置' }).click();
  await expect(page.getByRole('button', { name: /选择 D1 点足候选/ })).toBeDisabled();
  await page.getByRole('button', { name: '下一步：执行电脑' }).click();
  await expect(page.getByTestId('telemetry-state')).toContainText('UNKNOWN');
  await expect(page.getByTestId('battery-value')).toContainText('未知');
  await page.getByRole('button', { name: '下一步：部署预览' }).click();
  await expect(page.getByRole('button', { name: '开始 MOCK 演示' })).toBeEnabled();
  await page.getByRole('button', { name: '开始 MOCK 演示' }).evaluate((button) => {
    (button as HTMLButtonElement).click();
    (button as HTMLButtonElement).click();
  });
  await expect(page.getByRole('heading', { name: '演示流程完成（MOCK），未部署真机', exact: true })).toBeVisible();
  expect(submissionCount).toBe(1);
  const firstJob = await page.getByTestId('job-id').innerText();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/task6-mock-success.png', fullPage: true });
  await page.screenshot({ path: 'test-results/task6-mock-success-viewport.png', fullPage: false });
  await page.reload();
  await expect(page.getByTestId('job-id')).toHaveText(firstJob);
  await expect(page.getByRole('heading', { name: '演示流程完成（MOCK），未部署真机', exact: true })).toBeVisible();
  expect(submissionCount).toBe(1);
  await page.getByRole('button', { name: '新建演示' }).click();
  await page.getByLabel('演示场景').selectOption('verify_failure');
  await page.getByRole('button', { name: '4 部署预览' }).click();
  await expect(page.getByText('故障注入测试 · 验证步骤失败')).toBeVisible();
  await page.getByRole('button', { name: '开始 MOCK 演示' }).click();
  await expect(page.getByTestId('job-state')).toContainText('FAILED');
  await expect(page.getByText('MOCK_READINESS_FAILED', { exact: true }).first()).toBeVisible();
  await expect(page.getByText(/MOCK 故障注入：就绪检查失败；证据：<script>window.__d1env_injected=true<\/script>/).first()).toBeVisible();
  expect(await page.evaluate(() => '__d1env_injected' in window)).toBe(false);
  await expect(page.getByTestId('mock-watermark')).toContainText('MOCK');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/task6-mock-failure.png', fullPage: true });
  await page.screenshot({ path: 'test-results/task6-mock-failure-viewport.png', fullPage: false });
  const failedJob = await page.getByTestId('job-id').innerText();
  await page.reload();
  await expect(page.getByTestId('job-id')).toHaveText(failedJob);
  await expect(page.getByTestId('job-state')).toContainText('FAILED');
  await expect(page.getByRole('checkbox', { name: '遮盖 IP / 序列号' })).toBeChecked();
  await page.getByRole('button', { name: '生成去敏诊断报告' }).click();
  const jsonDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载 JSON' }).click();
  const json = await jsonDownload;
  expect(json.suggestedFilename()).toContain('mock');
  const jsonPath = await json.path();
  if (!jsonPath) throw new Error('下载未生成实际文件');
  const report = JSON.parse(await readFile(jsonPath, 'utf8')) as { mode: string; verified_scope: string; events: unknown[] };
  expect(report.mode).toBe('mock');
  expect(report.verified_scope).toBe('mock');
  expect(report.events.length).toBeGreaterThan(0);
  const markdownDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载 Markdown' }).click();
  expect((await markdownDownload).suggestedFilename()).toContain('mock');
  await page.getByRole('button', { name: '重试 MOCK 演示' }).click();
  await expect.poll(() => submissionCount).toBe(3);
  expect(keys[2]).not.toBe(keys[1]);
  expect(planIds[2]).toBe(planIds[1]);
  await expect(page.getByTestId('job-state')).toContainText('FAILED');
});
